### ISSUE TITLE
As an Endowment manager, I want to withdraw funds to the wallet of my choosing

### ISSUE THREAD

**Issue by SovereignAndrey** [AngelProtocolFinance/angelprotocol-web-app#1709]
**CU Ticket:** https://app.clickup.com/t/865bm3825
**Assigned To:** 
**Version:** v1.8

## Description of the issue
<p><strong>User Story:</strong><br/>As an Impact Entrepreneur, I want to send funds to the wallet of my choosing so that I can withdraw to my own account or send funds to a third-party</p>

Translation: Make sure the Withdraw Funds page, form, etc matches the Figma design.

**Comment by misicnenad** [comment]
Relevant Figma https://www.figma.com/file/sDjoeJ2IFPd9EJ1LI2WMvF/Product-Design?node-id=1790%3A44223&t=MiJ0n0e96rrbOed7-0

**Comment by misicnenad** [comment]
@SovereignAndrey should "Reason" (for withdrawal) field be removed? It is not present in Figma
![image](https://user-images.githubusercontent.com/19427053/221774650-6de8531e-8a3c-4592-8c45-e099f0a5c10c.png)

**Comment by misicnenad** [comment]
@SovereignAndrey presumably, this "clipboard" icon can be used to automatically paste anything that was last added to the user's machine's clipboard (last thing copied)?
![image](https://user-images.githubusercontent.com/19427053/221855094-e7835864-ab46-40b9-a233-ce02d609dfac.png)

**Comment by misicnenad** [comment]
@SovereignAndrey do we still need to display a warning stating `The minimum withdrawal for Ethereum & Binance is $20 USDC`?
This message is missing from Figma.
![image](https://user-images.githubusercontent.com/19427053/222158001-d5082281-e67e-46d2-91b5-a7c7388186be.png)
![image](https://user-images.githubusercontent.com/19427053/222158063-9c3e00c9-5178-4e91-aaa5-fbc0260807fc.png)

**Comment by misicnenad** [comment]
@SovereignAndrey what are the "Start Time" and "Actions" columns' purpose?
![image](https://user-images.githubusercontent.com/19427053/222230016-319460d2-89bf-4fbe-8232-62178f360481.png)

We currently do not have a `start_time` (or any `date` type) field when querying withdrawals. Do we just need to update AWS to return it @jp-mariano ?

**Comment by SovereignAndrey** [comment]
> @SovereignAndrey do we still need to display a warning stating `The minimum withdrawal for Ethereum & Binance is $20 USDC`? This message is missing from Figma. ![image](https://user-images.githubusercontent.com/19427053/222158001-d5082281-e67e-46d2-91b5-a7c7388186be.png) ![image](https://user-images.githubusercontent.com/19427053/222158063-9c3e00c9-5178-4e91-aaa5-fbc0260807fc.png)

That warning stays in.

**Comment by SovereignAndrey** [comment]
> @SovereignAndrey should "Reason" (for withdrawal) field be removed?

That stays in for the locked withdraws (only used by charities).

**Comment by SovereignAndrey** [comment]
> @SovereignAndrey presumably, this "clipboard" icon can be used to automatically paste anything that was last added to the user's machine's clipboard (last thing copied)? 

That's a really strange UI/UX. Drop it for now. :+1:

**Comment by SovereignAndrey** [comment]
> @SovereignAndrey what are the "Start Time" and "Actions" columns' purpose?

I assume "start time" is when the withdraw was submitted. Not sure what "actions" would be. We can drop that for now and add it later. 

> We currently do not have a `start_time` (or any `date` type) field when querying withdrawals. Do we just need to update AWS to return it @jp-mariano ?

Yes, returning a start datetime field would be needed. cc: @jp-mariano. 
 
> @SovereignAndrey should `Amount` column contain the "requested amount" or the "amount received"?

Amount requested would go there.

**Comment by jp-mariano** [comment]
> We currently do not have a `start_time` (or any `date` type) field when querying withdrawals. Do we just need to update AWS to return it @jp-mariano ?
>> Yes, returning a start datetime field would be needed. cc: @jp-mariano.

Yes, we can add a `start_time` field. This can be made every time a withdraw record is created.

**Comment by misicnenad** [comment]
@SovereignAndrey is the "copy address" icon really necessary here? It's not hard to implement, just seems redundant.
![image](https://user-images.githubusercontent.com/19427053/222361070-b28faa7a-7b53-40d0-9e0d-f6e26cc5efaf.png)

**Comment by misicnenad** [comment]
@SovereignAndrey how will the user know which crypto they withdrew when there's no currency indication? Do we add a "Currency" column as in Donations table?

**Comment by SovereignAndrey** [comment]
> @SovereignAndrey how will the user know which crypto they withdrew when there's no currency indication? Do we add a "Currency" column as in Donations table?

It is always USDC being withdrawn from the accounts contract.

**Comment by misicnenad** [comment]
> > @SovereignAndrey presumably, this "clipboard" icon can be used to automatically paste anything that was last added to the user's machine's clipboard (last thing copied)?
> 
> That's a really strange UI/UX. Drop it for now. 👍

@SovereignAndrey it seems this icon navigates the user to the Proposal page related to the selected withdrawal.
![image](https://user-images.githubusercontent.com/19427053/222378657-50fa4959-2eae-4e27-bd41-c45a21056e9c.png)

**Comment by misicnenad** [comment]
@jp-mariano since the tables require the addition of the "Load More" btn, we will need to enable the `GET /v1/withdraw/{address}` endpoint to return paginated results, similar to how `GET /v3/endowments/${network}` works.

**Comment by SovereignAndrey** [comment]
> @SovereignAndrey when should this notification appear and what does clicking on it do?

I imagine it appears if there are open withdraws (proposals needing votes/approval) for that endowment. 

Clicking the link should take them to the proposals page (ie. decision center page).
