### ISSUE TITLE
Move existing Admin pages/components to align with new Sidebar setup

### ISSUE THREAD

**Issue by SovereignAndrey** [AngelProtocolFinance/angelprotocol-web-app#1720]
Original CU ticket: https://app.clickup.com/t/865bm380k

Pages required for NPOs from MVP screenshot should be populated from existing Admin / Dashboard pages and components where possible.

**Comment by misicnenad** [comment]
`Contributions` should be the current `/donations/{address}` page (My Donations)?

**Comment by SovereignAndrey** [comment]
> Original CU ticket: https://app.clickup.com/t/865bm380k
> 
> Pages required for NPOs from MVP screenshot should be populated from existing Admin / Dashboard pages and components where possible. 

Contributions would be a page containing the title "Contributions" as well as the table that endowments see with all their donors contributions to them (moved from the dashboard where it sits today)

**Comment by misicnenad** [comment]
> > Original CU ticket: https://app.clickup.com/t/865bm380k
> > Pages required for NPOs from MVP screenshot should be populated from existing Admin / Dashboard pages and components where possible.
> 
> Contributions would be a page containing the title "Contributions" as well as the table that endowments see with all their donors contributions to them (moved from the dashboard where it sits today)

Oh, I misunderstood the requirements originally. All clear now.
