### ISSUE TITLE
Registration flow provides option to have APES process cash donations for them (only available if Origin country is in approved list) (reg portal)

### ISSUE THREAD

**Issue by SovereignAndrey** [AngelProtocolFinance/angelprotocol-web-app#1764]
**CU Ticket:** https://app.clickup.com/t/865bpjfuq
**Assigned To:** 
**Version:** v1.8

**Comment by misicnenad** [comment]
@SovereignAndrey what are the exact requirements here, how does regi. flow "provide option" to have APES process cash donations?

**Comment by SovereignAndrey** [comment]
> @SovereignAndrey what are the exact requirements here, how does reg. flow "provide option" to have APES process cash donations?

Probably in documentation part, section 1 for now, show a checkbox to opt in. Add new field to data sent to aws. Cc: @jp-mariano

**Comment by jp-mariano** [comment]
Just to be clear, is this different from the Kado Fiat pipeline?

Regardless, I think we can just have a hard-coded list of the supported countries in the `registration-update` Lambda. If the `HqCountry` they provided hits some country in our list then we could create a field with `boolean` value (`CashEligible == true`) which will indicate if they are eligible for cash donation processing by APES.

**Comment by SovereignAndrey** [comment]
> Just to be clear, is this different from the Kado Fiat pipeline?
> 
> Regardless, I think we can just have a hard-coded list of the supported countries in the `registration-update` Lambda. If the `HqCountry` they provided hits some country in our list then we could create a field with `boolean` value (`CashEligible == true`) which will indicate if they are eligible for cash donation processing by APES.

Correct! This is where charities will be able to first opt into using the fiat pipelines(if eligable). Because this is not a feature we can legally offer charities with HQ outside of a certain set of countries (I will try to pin down the exact list, but it's short). 

@misicnenad for now we are only need to worry about the general checks. Ie. Given hq country is in some approved list (probably best stored in an AWS for easy updating), show that check box. Otherwise, it will be false. 

There's another bit of v2 logic check we will add later like: 
IFF country HQ in ShortList && Reg ID/Number given had a match to a known charity in that country's official DB 
THEN Show checkbox to allow opt in
ELSE set to false

**Comment by SovereignAndrey** [comment]
> Do we have a list of countries at the moment which we wish to hard code for this checks visibility ? 
> Please provide the list or api to fetch that list @SovereignAndrey 

Only eligible charities are ones from countries (ie. HQ country) of: US, UK, & NZ

**Comment by SovereignAndrey** [comment]
> @SovereignAndrey please let me know if the text needs to be changed for this checkbox

Look good to me.

**Comment by jp-mariano** [comment]
> I am introducing a checkbox "cashEligible" at the bottom which will be visible only for whitelisted countries like this (by default it will send value false), can you make necessary change in the backend API @jp-mariano so you can accept this attribute in the body params of the api

Yep, will do. Also, please pass the new field as `CashEligible` just to be uniform with the existing DB fields. Thank you.
