### ISSUE TITLE
Header/Footer components refactored to be able to generate custom links based on externally defined objects/lists

### ISSUE THREAD

**Issue by SovereignAndrey** [AngelProtocolFinance/angelprotocol-web-app#1766]
**CU Ticket:** https://app.clickup.com/t/865bm3aby
**Assigned To:** Nenad Misic
**Version:** v1.8

## Description of the issue
<p>Footer&#x2F;Header accept constants which are set of links for the given AIF vs NPO.</p>

**Comment by misicnenad** [comment]
@SovereignAndrey does this include socials links? Should header logo be configurable as well?

**Comment by SovereignAndrey** [comment]
> @SovereignAndrey 
> 
> 1. Does this include socials links?
> 2. Should header logo be configurable as well?
> 3. Should newsletter be changed in any way for AIF vs NPO?

1. Maybe, but we can always change the social media links in that file to customize them I think.
2. Yes
3. I don't think that will change. It can be a future modification if needed.
