### ISSUE TITLE
1.7.1 testing - add a link to the register help page on the register page itself.

### ISSUE THREAD

**Issue by SovereignAndrey** [AngelProtocolFinance/angelprotocol-web-app#1813]
CU #: 862j92rqm - https://app.clickup.com/t/862j92rqm
Created on: Feb 17 2023 
Original Creator: Tim Stirrup

## Description
<p>&#x27;Need some help? Click here&#x27; kind of thing that goes here - <br/>Unmanaged custom blot!</p>

**Comment by abbasali1994** [comment]
The help Link provided is not working

**Comment by SovereignAndrey** [comment]
@abbasali1994 Tim provided correct link in the CU ticket. 👍

**Comment by SovereignAndrey** [comment]
> @SovereignAndrey @abbasali1994 there is a simple way to have the article open inside the Intercom chatbox inside our webapp, so that users always stay inside our app:
> ![image](https://user-images.githubusercontent.com/19427053/221769329-06a218f2-b725-4043-a3fb-4a89bb773de5.png)
> 
> [Link to official docs](https://developers.intercom.com/installing-intercom/docs/intercom-javascript#intercomshowarticle-articleid) on how to do this. For `articleId` we can use `6628120` from the provided URL `https://intercom.help/angel-giving/en/articles/6628120-how-do-i-sign-up-register-as-a-charity`

Awesome! We should do that then. :100:

**Comment by misicnenad** [comment]
> Awesome! We should do that then. 💯

Just confirming this with Tim to see if we get a green light from him too!

**Comment by misicnenad** [comment]
Tim confirmed the requirement https://app.clickup.com/t/862j92rqm?comment=90100007449068
