### ISSUE TITLE
Fix error appearing when saving a cropped image (in modal)

### ISSUE THREAD

**Issue by SovereignAndrey** [AngelProtocolFinance/angelprotocol-web-app#1815]
CU #: 86774j3h9 - https://app.clickup.com/t/86774j3h9
Created on: Jan 13 2023 
Original Creator: Nenad Misic

## Description
<p>Steps to reproduce:</p><ol><li>Go to &quot;Edit profile&quot; page</li><li>Click on either banner or logo to update them</li><li>Pick a new image &amp; set crop</li><li>Click on &quot;Save&quot; btn in top right</li><li><strong>Expected:</strong> modal closes and image is cropped.</li><li><strong>Actual:</strong> image is cropped, but modal stays open and error appears in console.</li></ol><p><br/><img src="https://t20472266.p.clickup-attachments.com/t20472266/1aa5efd9-b5ed-4619-9762-b3b23dc6f9c1/image.png"/></p>

**Comment by abbasali1994** [comment]
Cant replicate the issue on my localhost , already fixed
