### ISSUE TITLE
1.7.1 testing - Widget remove ability to choose percentage

### ISSUE THREAD

**Issue by SovereignAndrey** [AngelProtocolFinance/angelprotocol-web-app#1817]
CU #: 862j922z7 - https://app.clickup.com/t/862j922z7
Created on: Feb 17 2023 
Original Creator: Tim Stirrup

## Description
<p>the choice of endowment&#x2F;current has always been the donors - with the new widget, the charity COULD force everything into current account. Which we don&#x27;t really want.<br/><br/>Should this option be left out as it changes the very relationship donors have with the charity? <br/>

**Comment by abbasali1994** [comment]
@SovereignAndrey Ticket seems to be closed after discussion among team members
(Checked  last comment from chauncey)
