### ISSUE TITLE
Fix "Tag type 'donations' was used, but not specified in `tagTypes`" error

### ISSUE THREAD

**Issue by SovereignAndrey** [AngelProtocolFinance/angelprotocol-web-app#1824]
CU #: 37bu62w - https://app.clickup.com/t/37bu62w
Created on: Dec 1 2022 
Original Creator: Nenad Misic

## Description
<p>Repro steps:</p><ul><li>start webapp</li><li>open browser console (click F12 on keyboard)</li><li>connect Keplr wallet with AP team account</li><li>click on connected wallet dropdown button</li><li>click &quot;My Donations&quot; link</li><li>error appears in console logs</li></ul>

**Comment by ap-justin** [comment]
already fixed before `"donation"` tag type is already added
