### ISSUE TITLE
On Marketplace read just those endowment fields necessary to display Cards

### ISSUE THREAD

**Issue by SovereignAndrey** [AngelProtocolFinance/angelprotocol-web-app#1828]
CU #: 861m8jnxf - https://app.clickup.com/t/861m8jnxf
Created on: Jan 19 2023 
Original Creator: Nenad Misic

## Description
<p>Currently to display <code>Cards</code>  all the endowment fields need to be fetched even though only a subset of those is used. Fetching only those fields necessary to display <code>Cards</code> will reduce network bandwidth usage for users.<br/><br/>See Paolo&#x27;s comment explaining how to do this on the link below:<br/><a href="https://github.com/AngelProtocolFinance/angelprotocol-web-app/pull/1640#issuecomment-1396372778" target="_blank">https:&#x2F;&#x2F;github.com&#x2F;AngelProtocolFinance&#x2F;angelprotocol-web-app&#x2F;pull&#x2F;1640#issuecomment-1396372778</a></p>

**Comment by ap-justin** [comment]
already implemented by #1652
