### ISSUE TITLE
Add support for switching chains to XDefi wallet

### ISSUE THREAD

**Issue by SovereignAndrey** [AngelProtocolFinance/angelprotocol-web-app#1829]
CU #: 34agd86 - https://app.clickup.com/t/34agd86
Created on: Nov 24 2022 
Original Creator: Nenad Misic

## Description
<p>All the other wallets currently support this feature except for XDefi. The reason for this is that XDefi logic is built from combining evm-specific code &amp; terra-related code, which are currently split from each other.<br/>Will need to reintroduce the <code>useXdefi</code>  hook in which XDefi data &amp; operations will be defined, including <code>supported chains</code>  and <code>function switchChain</code> .<br/><br/>Check out <a href="https://github.com/AngelProtocolFinance/angelprotocol-web-app/tree/xdefi-switching-backup" target="_blank">xdefi-switching-backup</a> branch to see the initial work (go to <code>useXdefi</code>  file). </p>

**Comment by abbasali1994** [comment]
Following feature is already working as per my testing
