### ISSUE TITLE
Align "My Donations" table styles with new Figma designs

### ISSUE THREAD

**Issue by SovereignAndrey** [AngelProtocolFinance/angelprotocol-web-app#1831]
CU #: 8677bgjkz - https://app.clickup.com/t/8677bgjkz
Created on: Feb 7 2023 
Original Creator: Nenad Misic

## Description
<p>Noticed the following, but there are probably more:</p><ul><li>table row colors (odd vs even colors)</li><li>donation row details on mobile</li><li>&quot;LOAD MORE&quot; button missing - Unmanaged custom blot! Unmanaged custom blot! do we even want this?</li></ul>

**Comment by misicnenad** [comment]
Some work was done as part of https://github.com/AngelProtocolFinance/angelprotocol-web-app/pull/1468, but more styles need to be updated (biggest missing piece is mobile view update).

**Comment by misicnenad** [comment]
@SovereignAndrey @lambi9891 is "LOAD MORE" button necessary? If so, we need to limit the `ItemCutoff` to `10` as per Figma @jp-mariano 
![image](https://user-images.githubusercontent.com/19427053/220882484-c13027bf-2f06-4ff7-8136-c8c0582b425e.png)

**Comment by SovereignAndrey** [comment]
> @SovereignAndrey @lambi9891 is "LOAD MORE" button necessary? If so, we need to limit the `ItemCutoff` to `10` as per Figma @jp-mariano 
> ![image](https://user-images.githubusercontent.com/19427053/220882484-c13027bf-2f06-4ff7-8136-c8c0582b425e.png)
> 

It probably is needed(pagination or a load more option), since there will eventually be users and Endowments that have lots and lots of records.
