### ISSUE TITLE
Remove redundant classNames from /Registration/common/Button.tsx

### ISSUE THREAD

**Issue by SovereignAndrey** [AngelProtocolFinance/angelprotocol-web-app#1832]
CU #: 319ank7 - https://app.clickup.com/t/319ank7
Created on: Oct 13 2022 
Original Creator: Nenad Misic

## Description
<p><a href="https://github.com/AngelProtocolFinance/angelprotocol-web-app/blob/RC-v1.7/src/pages/Registration/common/Button.tsx" target="_blank">&#x2F;Registration&#x2F;common&#x2F;Button.tsx</a><br/><br/>Since the button styles are handled by the <code>btn-orange</code> , <code>btn-outline-orange</code>  etc., the <code>className</code>  for this shared button component should basically be:<br/><code>className={props.className}</code> ➝  to allow for passing in custom widths, heights and <code>btn-[orange&#x2F;blue]</code>  classes</p>

**Comment by ap-justin** [comment]
closed with 
* #1678
