### ISSUE TITLE
Fix "dark theme" being set on page reload even when light theme was previously selected

### ISSUE THREAD

**Issue by SovereignAndrey** [AngelProtocolFinance/angelprotocol-web-app#1854]
(edit by @misicnenad : running this on Windows (don't judge, I still prefer Linux) with "dark theme" turned on system-wide, using Brave browser)

Repro steps:
- open webapp
- dark theme is set by default
- switch to light theme
- reload page
- **expected**: webapp loads in light theme
- **actual**: webapp loads in dark theme

**Comment by SovereignAndrey** [comment]
@misicnenad Cannot reproduce this on Chrome (on `master` branch). I tested on the marketplace, leaderboard, and on the profile page. Neither hard nor soft refresh yielded a reversion of the theme back to dark when I started on light mode. 

What branch / browser are you using? What page were you on when you saw this behavior?

**Comment by misicnenad** [comment]
> @misicnenad Cannot reproduce this on Chrome (on `master` branch). I tested on the marketplace, leaderboard, and on the profile page. Neither hard nor soft refresh yielded a reversion of the theme back to dark when I started on light mode.
> 
> What branch / browser are you using? What page were you on when you saw this behavior?

Using Brave and just tested this on master branch.
