### ISSUE TITLE
widget on mobile view

### ISSUE THREAD

**Issue by SovereignAndrey** [AngelProtocolFinance/angelprotocol-web-app#1861]
CU #: 8677gdhz8 - https://app.clickup.com/t/8677gdhz8
Created on: Feb 24 2023 
Original Creator: Tim Stirrup

## Description
<p>the widget connect doesn&#x27;t work correctly on the mobile view. <br/><br/>each wallet connect option has a slightly different error! <br/><br/>see the attached video. </p>

**Comment by abbasali1994** [comment]
Findings for terramobile wallet:
The issue is that session timesout when terra mobile station is triggered, didnt find any documentation on how to fix this

**Comment by abbasali1994** [comment]
Issue is resolved for keplr mobile after the latest extension update and walletprovider update

**Comment by abbasali1994** [comment]
@SovereignAndrey pls suggest next steps for this ticket , based on my findings issues seem more related to the providers mobile app counterparts

**Comment by SovereignAndrey** [comment]
Thanks for looking into this and confirming it's working on mobile. :+1: I'll close this ticket now.
