### ISSUE TITLE
Admin Withdraw: Re-wired to send msgs to Polygon contracts

### ISSUE THREAD

**Issue by SovereignAndrey** [AngelProtocolFinance/angelprotocol-web-app#1911]
Withdraw supported networks in v1.8:
- Polygon (obviously!)
- Ethereum
- Biniance

**Comment by misicnenad** [comment]
@SovereignAndrey which networks should be supported for withdrawal then, only Juno and Polygon?
What about the currently "available" (but not really) Ethereum and Binance? Should we remove them since the user is unable to withdraw to addresses on those networks (as per code in the [useWithdraw](https://github.com/AngelProtocolFinance/angelprotocol-web-app/blob/RC-v1.8/src/pages/Admin/Charity/Withdraws/Withdrawer/WithdrawForm/useWithdraw.ts#L35), used to submit the withdrawal):
```ts
...
    const isJuno = data.network === chainIds.juno;
    //if not juno, send to ap wallet (juno)
    const beneficiary = isJuno ? data.beneficiary : ap_wallets.juno_withdraw;
...
```

**Comment by SovereignAndrey** [comment]
> @SovereignAndrey which networks should be supported for withdrawal then, only Juno and Polygon?
> 
> What about the currently "available" (but not really) Ethereum and Binance? Should we remove them since the user is unable to withdraw to addresses on those networks (as per code in the [useWithdraw](https://github.com/AngelProtocolFinance/angelprotocol-web-app/blob/RC-v1.8/src/pages/Admin/Charity/Withdraws/Withdrawer/WithdrawForm/useWithdraw.ts#L35), used to submit the withdrawal):
> ```ts
> ...
>     const isJuno = data.network === chainIds.juno;
>     //if not juno, send to ap wallet (juno)
>     const beneficiary = isJuno ? data.beneficiary : ap_wallets.juno_withdraw;
> ...
> ```

@misicnenad We would need to support the same withdrawal logic we have today, in that if the withdrawal is to the native chain of the accessing Endowment, either Juno OR Polygon, then take the wallet address that is passed as the destination of the withdraw. If any other chain, then we need to move the funds to the AWS withdrawals wallet (Juno or Polygon depending on the native chain of the endowment being accessed) and do the usual POST to AWS to relay the x-chain withdrawal info.

**Comment by misicnenad** [comment]
@SovereignAndrey what are AP's `polygon withdraw` and `polygon deposit` addresses?
https://github.com/AngelProtocolFinance/angelprotocol-web-app/blob/RC-v1.8/src/constants/ap_wallets.ts

**Comment by misicnenad** [comment]
@SovereignAndrey 
> If any other chain, then we need to move the funds to the AWS withdrawals wallet (Juno or Polygon depending on the native chain of the endowment being accessed) and do the usual POST to AWS to relay the x-chain withdrawal info.

But the withdrawal proposal is created only on Juno?

Our current code looks like below (here's [link to source](https://github.com/AngelProtocolFinance/angelprotocol-web-app/blob/RC-v1.8/src/pages/Admin/Charity/Withdraws/Withdrawer/WithdrawForm/useWithdraw.ts#L72)):
```ts
    await sendTx({
      msgs: [proposal],
      //Juno withdrawal
      ...propMeta,
      onSuccess: isJuno
        ? undefined //no need to POST to AWS if destination is juno
        : async (response, chain) =>
            await logProposal(
              {
                endowment_multisig: cw3,
                proposal_chain_id: chainIds.juno,
                target_chain: data.network,
                target_wallet: data.beneficiary,
                type: data.type,
              },
              response,
              chain
            ),
    });
```
You can see that the `proposal_chain_id` is set to Juno.

**Comment by SovereignAndrey** [comment]
> @SovereignAndrey @jp-mariano what are AP's `polygon withdraw` and `polygon deposit` addresses? https://github.com/AngelProtocolFinance/angelprotocol-web-app/blob/RC-v1.8/src/constants/ap_wallets.ts

@misicnenad @jp-mariano Polygon APES wallets are as follows:
- Deposits: `0x5a882Eb704EA153B117Ab2b1797bA46a1B09Da2c` (same as ETH and most all EVMs)
- Withdraws: `0x0189BeffF5B23E692Ea25C4820930c3c11e8D448`

**Comment by SovereignAndrey** [comment]
> But the withdrawal proposal is created only on Juno, no matter which chain the endowment is on?
> 
> Our current code looks like below (here's [link to source](https://github.com/AngelProtocolFinance/angelprotocol-web-app/blob/RC-v1.8/src/pages/Admin/Charity/Withdraws/Withdrawer/WithdrawForm/useWithdraw.ts#L72)):
> 
> You can see that the `proposal_chain_id` is set to Juno.

The withdraw proposal is created on the chain for which the Endowment exists on. If that's Juno, we create the proposal on Juno as we do today. If that's Polygon, then we would need to create the withdraw proposal on Polygon.

**Comment by misicnenad** [comment]
@SovereignAndrey 
> The withdraw proposal is created on the chain for which the Endowment exists on

How do we know which chain does the Endowment exist on? Our current code just assumes all endowments are on Juno, do we have some new field/backend logic to check the endowment's chain?

**Comment by SovereignAndrey** [comment]
> @SovereignAndrey 
> > The withdraw proposal is created on the chain for which the Endowment exists on
> 
> How do we know which chain does the Endowment exist on? Our current code just assumes all endowments are on Juno, our admin Guard assumes this as well (using the [appropriate hook](https://github.com/AngelProtocolFinance/angelprotocol-web-app/blob/master/src/services/juno/custom.ts#L106)), do we have some new field/backend logic to check the endowment's chain?
> 
> -------------------------------------------------------
> 
> Unrelated to previous, below is a couple of example flows to verify I understood the requirements correctly:
> ### 1. All on Juno
> - endowment is on Juno 
> - withdrawal address (beneficiary) is on Juno
> - create withdraw proposal on Juno
> 
> ### 2. Endowment on Juno, withdraw to Ethereum
> - endowment is on Juno 
> - withdrawal address (beneficiary) is on Ethereum
> - create withdraw proposal on Juno with target wallet being AWS withdraw wallet on Juno
> - log the Tx to AWS (set fields: `proposal_chain_id` is Juno, `target_chain` is Ethereum, `target_wallet` is beneficiary on Ethereum)
> 
> ### 3. Endowment on Polygon, withdraw to Juno
> - endowment is on Polygon
> - withdrawal address (beneficiary) is on Juno
> - create withdraw proposal on Polygon with target wallet being AWS withdraw wallet on Polygon
> - log the Tx to AWS (set fields: `proposal_chain_id` is Polygon, `target_chain` is Juno, `target_wallet` is beneficiary on Juno)
> 
> Flows check out?

@jp-mariano can please confirm these flows and the endowment id + chain differentiation in place for AWS endowments db records? Thanks!

**Comment by jp-mariano** [comment]
> @jp-mariano can please confirm these flows and the endowment id + chain differentiation in place for AWS endowments db records? Thanks!

Yep, will do. Thank you.

----

> How do we know which chain does the Endowment exist on? Our current code just assumes all endowments are on Juno, our admin Guard assumes this as well (using the appropriate hook), do we have some new field/backend logic to check the endowment's chain?

This will be addressed once we move the endowments DB into a new table which uses the `chain_id` and `id` (the endowment ID) as DB keys. New records will be scraped by the `registration-poll-querier` Lambda.

> Unrelated to previous, below is a couple of example flows to verify I understood the requirements correctly:

All flows are correct. Just a small reminder for flow 3 is that there's no infra in APES AWS right now which can scrape for Polygon withdraw proposals. This is yet to be made/refactor.

**Comment by SovereignAndrey** [comment]
@jp-mariano @misicnenad One idea might be to see if we could incorporate the Axelar JS SDK () into the web app UI to generate deposit addresses for cross-chain swaps. This would effectively eliminate the need for AWS to play the middle role! 

__Example 3 above would play out like:__
1. user enters the withdrawal address (beneficiary) is on Ethereum for example
**2. On submit we create the deposit address (via Axelar JS SDK) first**
3. create withdraw proposal on Polygon with target wallet being **Axelar deposit address** on Polygon
4. Endowment on Polygon is approved and executed, withdraws USDC to Polygon address.
5. Axelar takes over an routes the funds to the final chain/wallet

**Comment by SovereignAndrey** [comment]
> > @jp-mariano @misicnenad One idea might be to see if we could incorporate the Axelar JS SDK (https://docs.axelar.dev/dev/axelarjs-sdk/intro) into the web app UI to generate deposit addresses for cross-chain swaps. This would effectively eliminate the need for AWS to play the role of a mediator!
> 
> @SovereignAndrey , some points to think about:
> If we are to do this, we have to make sure that the withdrawn token is Axelar-wrapped (`axlUSDC`) or `WMATIC` or `MATIC`. Another thing to consider is the amount of time between the address being generated and the actual "execution" of the proposal. Based from the docs, https://docs.axelar.dev/dev/axelarjs-sdk/token-transfer-dep-addr (the first paragraph). "Deposit addresses generally function for up to 24 hours." If it exceed more than a day before execution, the generated deposit address might not work.

Good points! I was thinking of Ethereum passing USDC in and totally forgot that we always have to swap first to axlUSDC. Combined with the 24 hour limit on addresses you mentioned this idea is a total non-starter. 😮‍💨

**Comment by misicnenad** [comment]
@SovereignAndrey quoting [this Discord message](https://discord.com/channels/@me/877860812117647441/1090490153434357781):
> The multisig contract's (ie. the owner of an endowment or the AP Team multisig for example) transactions would take the place of proposals on the Proposals page.
And [this one from our chat](https://discord.com/channels/@me/914080167717138432/1090233150187249755):
> There are no multisig proposals on Polygon, only transactions that require a number of signatures to execute.

So when a withdrawal transaction is created for an endowment on Polygon to some other chain (e.g. Binance), **no proposal is created**, only a transaction that needs to be signed by some number of members. But this differs from the current Juno logic, which is to create a proposal and thus emit an event with the newly created proposal's `proposal_id`.
This is also what AWS expects, so we send it from the webapp (see [source](https://github.com/AngelProtocolFinance/angelprotocol-web-app/blob/RC-v1.8/src/pages/Admin/Charity/Withdraws/Withdrawer/WithdrawForm/useLogWithdrawProposal.ts#L34)). This means that AWS would also need to be updated to accommodate the Polygon flow - but how? @jp-mariano 

Questions:
1. What will we need to pass to AWS once a withdrawal some non-Polygon chain is initiated for an endowment on Polygon?
2. We can get a transaction ID, do we pass that? 
  2.1 How will that tie into the "Proposals" page?
3. Will we have to create a new page/component for Polygon withdrawals?

**Comment by SovereignAndrey** [comment]
@misicnenad Juno is gone and dead. :) All endowments and all funds for endowments will live on Polygon after the launch. Native USDC will be the token of donation. 

@jp-mariano separate, but pretty importantly, we ought to:
1. Make a clean version of the APIs for the v1.8 polygon contracts, distinct from the legacy Juno stuff that exists today. 
2. Create a new DB table for endowments on Polygon (like `endowments_polygon`) to use that will help keep things separate and removes all the need for reworking to use both endow ID & chain ID. 

We can probably leverage subgraph on the aws side to find the new multisig transactions, since those emitted events from the contracts will be queryable by both parties. If aws checks subgraph periodically and makes the link to what the web app reported by POSTing at the time of time of draft proposal creation we might be okay. 

Thoughts?

**Comment by jp-mariano** [comment]
> @jp-mariano separate, but pretty importantly, we ought to:
>
>  1.  Make a clean version of the APIs for the v1.8 polygon contracts, distinct from the legacy Juno stuff that exists today.
>  2.  Create a new DB table for endowments on Polygon (like endowments_polygon) to use that will help keep things separate and removes all the need for reworking to use both endow ID & chain ID.
>
> We can probably leverage subgraph on the aws side to find the new multisig transactions, since those emitted events from the contracts will be queryable by both parties. If aws checks subgraph periodically and makes the link to what the web app reported by POSTing at the time of time of draft proposal creation we might be okay.
>
> Thoughts?

I agree. Starting from a clean slate will be easier compared to making Cosmos code base run with EVM code base. We could leave the legacy Juno/Cosmos code base as is and start creating new Lambdas and other infra (DBs, CloudSearch domain, SQS queues) tailored for Polygon/EVM networks.

**Comment by SovereignAndrey** [comment]
> > @jp-mariano separate, but pretty importantly, we ought to:
> > 
> > 1. Make a clean version of the APIs for the v1.8 polygon contracts, distinct from the legacy Juno stuff that exists today.
> > 2. Create a new DB table for endowments on Polygon (like endowments_polygon) to use that will help keep things separate and removes all the need for reworking to use both endow ID & chain ID.
> > 
> > We can probably leverage subgraph on the aws side to find the new multisig transactions, since those emitted events from the contracts will be queryable by both parties. If aws checks subgraph periodically and makes the link to what the web app reported by POSTing at the time of time of draft proposal creation we might be okay.
> > Thoughts?
> 
> I agree. Starting from a clean slate will be easier compared to making Cosmos code base run with EVM code base. We could leave the legacy Juno/Cosmos code base as is and start creating new Lambdas and other infra (DBs, CloudSearch domain, SQS queues) tailored for Polygon/EVM networks.

Most of the logic will be the same, so we can likely re-use a lot of the existing code and wiring (with Polygon specific tweaks where needed). Ping me in Discord if you want to setup a separate call to plan / brainstorm.

**Comment by misicnenad** [comment]
> Remove Juno wiring.

@SovereignAndrey can we do this as part of a separate task to avoid expanding the scope of the current one?

**Comment by SovereignAndrey** [comment]
> > Remove Juno wiring.
> 
> @SovereignAndrey can we do this as part of a separate task to avoid expanding the scope of the current one?

@misicnenad SureI guess, if Polygon wiring is added here in such a way that replacing the Juno wiring at the same time wouldn't make sense? 

Please open a To Do ticket for that removal work. Also please ping the other devs in the group discord chat to open a discussion on approaches, so to make sure we're all on the same page for how to remove/refactor. Thanks! :+1:

**Comment by misicnenad** [comment]
> @misicnenad SureI guess, if Polygon wiring is added here in such a way that replacing the Juno wiring at the same time wouldn't make sense?
> 
> Please open a To Do ticket for that removal work. Also please ping the other devs in the group discord chat to open a discussion on approaches, so to make sure we're all on the same page for how to remove/refactor. Thanks! +1

@SovereignAndrey I though you meant all the withdrawal+proposal logic on Juno should be ripped out :sweat_smile: 
Will update withdrawal to only use Polygon.

**Comment by SovereignAndrey** [comment]
The proposal logic on Juno _should_ be ripped out. There's no need for it. We only need Polygon multisig logic in `v1.8`.

**Comment by stevieraykatz** [comment]
> Which exact contracts are we sending withdrawal requests to?

This should be exposed on the Accounts diamond at: 
`0xf725Ff6235D53dA06Acb4a70AA33206a1447D550`
