### ISSUE TITLE
AP Admin Multisig: Wiring added for existing methods on Juno to also work on Polygon

### ISSUE THREAD

**Issue by SovereignAndrey** [AngelProtocolFinance/angelprotocol-web-app#1912]

**Comment by ap-justin** [comment]
steps
- [ ] create directory from `src/contracts`--> `src/contracts/(juno | polygon)`
- [ ] create new service `services/polygon` like `services/juno`
- [ ] create types directory from `src/contracts` --> `src/contracts/(juno | polygon)`

**Comment by ap-justin** [comment]
addressed by #2028
