### ISSUE TITLE
Remove round borders around connector icons in the "select wallet" modal

### ISSUE THREAD

**Issue by SovereignAndrey** [AngelProtocolFinance/angelprotocol-web-app#1930]
Just remove `border border-prim` in https://github.com/AngelProtocolFinance/angelprotocol-web-app/blob/master/src/components/WalletSuite/WalletSelectorOpener/Connector.tsx#L26

Expected:
![image](https://user-images.githubusercontent.com/19427053/223970773-ff590209-8d92-4f46-97eb-939c9bcb7011.png)

Current:
![Image](https://user-images.githubusercontent.com/19427053/223982631-1738e321-569b-4f89-8a64-1898fcacffc1.png)

**Comment by Delyc** [comment]
I have worked on it and raised a PR.

**Comment by SovereignAndrey** [comment]
> I have worked on it and raised a PR.

Thank you so much for the help, Delyc! I'll take a look at your PR now. :)
