### ISSUE TITLE
urgent marketplace editing issues.

### ISSUE THREAD

**Issue by SovereignAndrey** [AngelProtocolFinance/angelprotocol-web-app#1973]
CU #: 862jg6t1j - https://app.clickup.com/t/862jg6t1j
Created on: Mar 23 2023 
Original Creator: Tim Stirrup

## Description
<p>Please see this message for details <a href="https://discord.com/channels/834976399228010527/857111094019883010/1088147435945197710" target="_blank">https:&#x2F;&#x2F;discord.com&#x2F;channels&#x2F;834976399228010527&#x2F;857111094019883010&#x2F;1088147435945197710</a><br/><br/>and this loom which illustrates both <br/><br/>Unmanaged custom blot!<br/><br/>and here&#x27;s another issue - not being able to change the HQ details - <br/><br/>Unmanaged custom blot!</p>

**Comment by misicnenad** [comment]
@SovereignAndrey just a note, the "Minified React error #321..." is something that started occurring due to some newly added/updated pkg (not sure which), but seems to not be affecting the webapp.

**Comment by misicnenad** [comment]
@SovereignAndrey it is possible to fix the TikTok URL issue, but this is not the first time we'd had to deal with a URL validation edge case. See [this comment on the related CU task](https://app.clickup.com/t/862jg6t1j?comment=90040006961312) for more context and details.

**Comment by misicnenad** [comment]
@SovereignAndrey about the HQ update bug, seems to be some data format mismatch between webapp and AWS, currently waiting for more info from @jp-mariano once he investigates on AWS side if something might be wrong there or if the data format should be updated on the webapp.

**Comment by jp-mariano** [comment]
> @SovereignAndrey about the HQ update bug, seems to be some data format mismatch between webapp and AWS, currently waiting for more info from @jp-mariano once he investigates on AWS side if something might be wrong there or if the data format should be updated on the webapp.

Regarding the HQ update bug, the updatooor Lambda is still expecting the old format of an `hq` object instead of the new `hq_country` field. A hot fix is already implemented and this should be ok now. 👌🏾
