### ISSUE TITLE
Remove duplicate "Crop" btn from `ImgEditor` that appears after a new image was uploaded+cropped

### ISSUE THREAD

**Issue by SovereignAndrey** [AngelProtocolFinance/angelprotocol-web-app#1982]
Duplicate introduced with PR #1807, see [the changed file](https://github.com/AngelProtocolFinance/angelprotocol-web-app/pull/1807/files#diff-1be54e94e339b63191fa8c031b12c0f7ef25b900b3b295842884f6e84855af30)

Repro steps:
- connect Charity 1 wallet on Juno
- go to http://localhost:4200/admin/1/edit-profile
- scroll to "Banner image of your organization"
- click "Upload" btn
- upload any image
- the duplicate button appears in top-left (see image below)
![Image](https://user-images.githubusercontent.com/19427053/227182557-2f2a7207-fb41-49da-a574-b2eebccf1f9c.png)

Reason for this is most likely that copy/paste was used instead of cut/paste when buttons were moved around, so the original was left in the [source code](https://github.com/AngelProtocolFinance/angelprotocol-web-app/pull/1807/files#diff-1be54e94e339b63191fa8c031b12c0f7ef25b900b3b295842884f6e84855af30):
![Image](https://user-images.githubusercontent.com/19427053/227186117-b956b35d-c600-4e02-bd22-c147b6a56fb7.png)

**Comment by satishkumarsajjan** [comment]
I opened a PR. Check it out once.
