### ISSUE TITLE
Prod (bug): Giftcard prompt overflows when message is long

### ISSUE THREAD

**Issue by SovereignAndrey** [AngelProtocolFinance/angelprotocol-web-app#1992]
![Image](https://user-images.githubusercontent.com/89639563/226845493-48e1d908-f696-4c01-a057-695b7d1740b4.png)

another option is to turn transaction hash to links

**Comment by abbasali1994** [comment]
we could also provide  a shorthand version of txn hash with a copy icon:   0E15.....997C6

**Comment by SovereignAndrey** [comment]
> we could also provide a shorthand version of txn hash with a copy icon: 0E15.....997C6

Possibly! We also need to add some line breaks. Maybe can link the TX hash to an explorer as well?
```
Failed to save giftcard code.
Kindly contact support@angelgiving.io
Transaction: https://some-explorer.io/tx/0E15.....997C6
```
