### ISSUE TITLE
Support Request 

filtering issue on marketplace


### ISSUE THREAD

**Issue by SovereignAndrey** [AngelProtocolFinance/angelprotocol-web-app#2124]
please see the loom here - https://www.loom.com/share/ada73b3bc9914736b26cc396ff299a73

**Comment by satishkumarsajjan** [comment]
Is it cool if I too work on it???

**Comment by SovereignAndrey** [comment]
> Is it cool if I too work on it???

Thanks for the offer! :smile: I've assigned you to it.
