### ISSUE TITLE
Support Request 

Tun Yat withdrawal failure request - URGENT


### ISSUE THREAD

**Issue by SovereignAndrey** [AngelProtocolFinance/angelprotocol-web-app#2130]
tu yat trying to withdraw from their current account using their existing JUNO wallet access - juno1vl95whglxvnzkegl2v3ptn6p0ea9yv9xwn3vr2

They are getting a withdrawal failure saying there is not enough balance. But are only trying to withdraw $100 from the 20,000 available. They have JUNO in their wallet. 

I have attached their first image and am getting an error report. 

Please report back asap. Thanks

https://api-eu1.hubspot.com/form-integrations/v1/uploaded-files/signed-url-redirect/67613826756?portalId=24900163&sign=rM8QYQ5OWpthMmLwOxMYhjR5bt4%3D&conversionId=26167fe3-5b28-46de-9f48-8acf255a2764&filename=26167fe3-5b28-46de-9f48-8acf255a2764-TICKET.supporting_information-image-(1).png

**Comment by angelprotocol-validator** [comment]
closed - user error!
