### ISSUE TITLE
Admin section should have a default fallback URL

### ISSUE THREAD

**Issue by misicnenad** [AngelProtocolFinance/angelprotocol-web-app#2153]
**Describe the bug**
When in admin section and the user types in a URL that does not exist within the app, it should fallback to some valid URL, the best candidate being the Admin Dashboard (@SovereignAndrey can confirm which exact page this should be).

For example this URL does not exist http://localhost:4200/admin/55/fdsafda but it will cause the page to remain on said URL and just display nothing (see image below):
![image](https://user-images.githubusercontent.com/19427053/236806448-5cbd3f79-bd10-4de1-9587-6f1c2afbf80c.png)

**To Reproduce**
1. In the URL bar type in some non-existent path, like http://localhost:4200/admin/55/fdsafda
2. Verify that nothing appears

**Expected behavior**
The page should automatically navigate to some fallback URL, probably Dashboard `http://localhost:4200/admin/{{ENDOW_ID}}`. We have the same behavior for other app sections, like in the root ones for charities the Marketplace is the fallback and for ASTs the Launchpad is the fallback page.

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04
 - Browser chrome
 - Version 113.0.5672.63

**Comment by SovereignAndrey** [comment]
@misicnenad Having a fallback to the Admin Dashboard for routes in admin area makes sense. All other URLs would fall back to index page (ie. Marketplace for Charities or Registration page for ASTs).
