### ISSUE TITLE
Locked account withdraw changes

### ISSUE THREAD

**Issue by SovereignAndrey** [AngelProtocolFinance/angelprotocol-web-app#2160]
CU #: 860qnzqt5 - https://app.clickup.com/t/860qnzqt5
Created on: Apr 28 2023 
Original Creator: Tim Stirrup

## Description
<p>you can only withdraw from current account <br/><br/>See attachment<br/><br/></p>

## COS
- [x] All Endowments should be able to see both Locked and Liquid withdraw options
    - [x] Charity Endowments tab labels: Locked ("Endowment") and Liquid ("Current")
    - [x] Normal Endowments tab labels: Locked ("Locked") and Liquid ("Liquid")
- [ ] Locked withdraw form tab points to the "Locked Withdraw" contract, sending the early locked withdraw "propose" message. See: https://github.com/AngelProtocolFinance/evm-smart-contracts/blob/merge-pedals/contracts/normalized_endowment/locked-withdraw/LockedWithdraw.sol
    - [x] There will no longer be a need for passing a Beneficiary on the Locked Withdraws, as all locked withdraws will flow to the liquid accounts of the requesting Endowment. Remove the address input field on the Locked form. 
- [ ] Liquid withdraw form points to the Accounts contract sending a withdraw message as usual for all endowments. See: https://github.com/AngelProtocolFinance/evm-smart-contracts/blob/merge-pedals/contracts/core/accounts/facets/AccountDepositWithdrawEndowments.sol#LL437C9-L437C9. The withdraw can support making a withdraw to an EOA address OR to an Endowment ID. We can leave the form as is for now, allowing only an address input (under the `address curBeneficiaryAddress`) and passing a `0` for `uint32 curBeneficiaryEndowId`. I will make a ticket to cover the UI changes needed to support endowment >> endowment liquid withdraws later.

**Comment by SovereignAndrey** [comment]
@abbasali1994 Please doubled check that the web app has correct logic and wiring to handle the two last COS (added recently) and ping when a PR is ready. Thanks!

**Comment by abbasali1994** [comment]
@SovereignAndrey as per my understanding and debugging of the code the following code justifies the last 2 COS points , covering the two contracts which need to be dealt with as per charity lock conditions

```
const [data, dest] = isLockedCharity
    ? encodeTx("locked-withdraw.propose", {
        id,
        beneficiary,
        addresses,
        amounts,
      })
    : encodeTx("accounts.withdraw", {
        id,
        type: accType,
        beneficiary,
        addresses,
        amounts,
      });
```

The following is present in the construction function called within withdraw function of the page

**Comment by SovereignAndrey** [comment]
> @SovereignAndrey as per my understanding and debugging of the code the following code justifies the last 2 COS points , covering the two contracts which need to be dealt with as per charity lock conditions
> 
> ```
> const [data, dest] = isLockedCharity
>     ? encodeTx("locked-withdraw.propose", {
>         id,
>         beneficiary,
>         addresses,
>         amounts,
>       })
>     : encodeTx("accounts.withdraw", {
>         id,
>         type: accType,
>         beneficiary,
>         addresses,
>         amounts,
>       });
> ```
> 
> The following is present in the construction function called within withdraw function of the page

@abbasali1994 We'll actually need a new set of changes to this withdraw form to sync with some changes to the product requirements (as of last night!). I'll update the ticket with new COS.

**Comment by abbasali1994** [comment]
Pls share links of the new contracts to refer from once ready, the above links don't seem to work now 
no merge-padals branch found @SovereignAndrey

**Comment by SovereignAndrey** [comment]
> Pls share links of the new contracts to refer from once ready, the above links don't seem to work now 
> no merge-padals branch found @SovereignAndrey 

Merge-petals was merged into master today. Same files/lines,just change to master branch.
