### ISSUE TITLE
Admin Area: Disable submit buttons & have read only input fields for non-connected wallet users

### ISSUE THREAD

**Issue by SovereignAndrey** [AngelProtocolFinance/angelprotocol-web-app#2176]
## COS
- [x] Hide the SWITCH button on sidebar menu when: no wallet is connected OR there is less then 2 ASTs associated with the connected wallet  
- [x] When a user is on the Admin area of the site, without a wallet connected, the following UI should be seen:
    - [x] all "Submit" buttons or other "action" buttons/links should be hidden
    - [x] all input fields, where possible, should be disabled
- [x] When a user has a wallet connected, everything should be active (is it exists today)

NOTES: @ap-justin 
- [ ] ~~lock forever buttons on individual settings page~~ design not final

![Image](https://github.com/AngelProtocolFinance/angelprotocol-web-app/assets/89639563/87e2db1a-0bf9-47f4-bd1e-bee2b2472f17)

**Comment by SovereignAndrey** [comment]
@abbasali1994 UI will differ slightly for the Admin area vs the rest of the site (donation and registration) since we're dealing with input/submissions that are restricted to a subset of wallets only and not open to the public to submit to. By hiding the buttons when a user is viewing the page without a wallet connected it removes the ability to click a button in the first place. Showing a popup message to connect a wallet to a user that is not involved with the AST/Charity Endowment is not helpful, since even if they connect a wallet then they'll be shown an error message an risk spending gas on a failed transaction. We're basically trying to move towards a read-only mode of the Admin pages.

**Comment by abbasali1994** [comment]
Understood, I will implement this logic specifically for Admin pages then , disable submit button and input fields unless wallet connected in polygon network and within the subset of wallets of that particular AST
