### ISSUE TITLE
Support Request 

editing site on mobile phone


### ISSUE THREAD

**Issue by SovereignAndrey** [AngelProtocolFinance/angelprotocol-web-app#2191]
When connected in keplr and having clicked on the admin button, you don't see the menu of admin items.

**Comment by ap-justin** [comment]
> When connected in keplr and having clicked on the admin button, you don't see the menu of admin items.

@SovereignAndrey,  for `master`, the admin menu is part of the main menu
<img width="446" alt="image" src="https://github.com/AngelProtocolFinance/angelprotocol-web-app/assets/89639563/fe70464e-4472-4a4c-8ed0-71f52b308f95">

let me know if this is not the one missing

**Comment by SovereignAndrey** [comment]
> > When connected in keplr and having clicked on the admin button, you don't see the menu of admin items.
> 
> @SovereignAndrey, for `master`, the admin menu is part of the main menu <img alt="image" width="446" src="https://user-images.githubusercontent.com/89639563/240793999-fe70464e-4472-4a4c-8ed0-71f52b308f95.png">
> 
> let me know if this is not the one missing

This is opened by Tim, the bridge just uses my account to open tickets here :sweat:, can you ping him in Discord to clarify? Thanks!

**Comment by ap-justin** [comment]
> This is opened by Tim, the bridge just uses my account to open tickets here :sweat:, can you ping him in Discord to clarify? Thanks!

no worries ser - reached out to him

**Comment by ap-justin** [comment]
@SovereignAndrey, confirmed with ser Tim that this is indeed what he was looking for - closed issue
