### ISSUE TITLE
Support Request 

unable to process withdraw to binance


### ISSUE THREAD

**Issue by SovereignAndrey** [AngelProtocolFinance/angelprotocol-web-app#2304]
Charity Endowment 147 is unable to withdraw to their Binance account - they have done this before successfully. 

see the screenshot of the error message:
![scrnshot](https://github.com/AngelProtocolFinance/angelprotocol-web-app/assets/85138450/6978f840-31d7-4708-b062-1bba90df29c2)

**Comment by angelprotocol-validator** [comment]
Can you let me know when this fix is applied -the charity is asking for an update. I have told them it is in progress.
